name: Main Branch

on:
  push:
    branches: [ "main" ]
    paths:
      - 'gpras/**'
      - 'Dockerfile'
      - '.dockerignore'

permissions:
  contents: read
  packages: write

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract version from gpras
        id: get_version
        shell: pwsh
        run: |
          $version = python -c "import gpras; print(gpras.__version__);"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

  docker-build-push:
    needs: get-version
    uses: ./.github/workflows/docker-build.yaml
    with:
      push_to_registry: true
      version: ${{ needs.get-version.outputs.version }}
      branch: 'main'
      platforms: 'linux/amd64'
