name: PR Checks

on:
  pull_request:
    branches: [ "main", "dev" ]

  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Ruff linting
        run: ruff check

  mypy-type-check:
    runs-on: ubuntu-latest
    name: Type check with mypy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        pip install "numpy>=2.0.0" .[dev]
    - name: Run mypy
      run: |
        MYPYPATH=gpras mypy gpras production

  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract version from gpras
        id: get_version
        shell: pwsh
        run: |
          $version = python -c "import gpras; print(gpras.__version__);"
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

  docker-build-test:
    needs: get-version
    uses: ./.github/workflows/docker-build.yaml
    with:
      push_to_registry: false
      version: ${{ needs.get-version.outputs.version }}
      branch: ${{ github.base_ref }}
      platforms: 'linux/amd64'
